### ISSUE TITLE
Add Jira integration

### ISSUE THREAD

**Issue by echoboomer** [echoboomer/incident-bot#140]
It could be useful to add a Jira integration so issues can be created in relation to incidents.

**Comment by oliverisaac** [comment]
This would be a great addition! We brought up moving to incidentbot.io and jira was an immediate hard-stop.

**Comment by echoboomer** [comment]
Thanks for the feedback! I'm actively working on this and it should be released today or tomorrow.

**Comment by echoboomer** [comment]
This has been implemented with the latest release `v1.4.0`.
