### ISSUE TITLE
Verify whether or not integration APIs need pagination

### ISSUE THREAD

**Issue by echoboomer** [echoboomer/incident-bot#147]
Integration APIs generally haven't been implemented with pagination which may be a problem for larger orgs. We should go through and verify for each one whether or not endpoints being used will need pagination or other types of protection.

**Comment by virgileJT** [comment]
hello, here is my change in client.py

`def store_slack_user_list():
    """
    Retrieves list of users from Slack organization and stores them using a clean format
    to be retrieved locally to avoid querying the Slack API every time this data
    is desired
    """
    try:
        cursor = ""
        users_array = []
        while True:
            resp = slack_web_client.users_list(cursor=cursor, limit=200)
            cursor = resp['response_metadata']['next_cursor']

            if resp.status_code == 200:
                for user in resp["members"]:
                    users_array += [(
                        {
                            "name": user["name"],
                            "real_name": user["profile"]["real_name"],
                            "id": user["id"],
                        }
                    )]
            else:
                logger.error(f"store_slack_user_list failed to build the list: {error}")
                break

            # if fewer items in current response than asked for, we're at the end
            if not cursor:
                break

        jdata = sorted(users_array, key=lambda d: d["name"])
...
`
