### ISSUE TITLE
emoji documentation

### ISSUE THREAD

**Issue by LanceSandino** [echoboomer/incident-bot#178]
There should be documentation around what emojis should be created and even examples/downloads of them to import to the slack channel.

**Comment by echoboomer** [comment]
The only custom emoji the app supports is the one you set in your config for creating an incident from a reaction.

https://github.com/echoboomer/incident-bot/blob/main/backend/config.yaml#L37

Everything else is in the standard Slack emoji kit.

**Comment by LanceSandino** [comment]
Interesting, I thought I had saw a :thumbtack: emoji somewhere... disregard. .Thanks!
