### ISSUE TITLE
zoom puts people in waiting room

### ISSUE THREAD

**Issue by LanceSandino** [echoboomer/incident-bot#191]
Setting up the `Server-to-Server Oauth` was working about a week ago, now when the meeting is created, people are thrown in a waiting room and it won't start.

I have reached out to Zoom but haven't heard anything. My first assumption was something in the API changed? 

We have default zoom waiting rooms off, and allow people to join meetings without the host.

**Comment by echoboomer** [comment]
I was able to reproduce this. I only have a user account, not a paid account, so I can't troubleshoot further. I was required to change these settings before I got it to work:

![image](https://user-images.githubusercontent.com/19732751/227806906-2327bd2d-4277-4f6f-b1ef-892fc8e4eb40.png)

![image](https://user-images.githubusercontent.com/19732751/227806925-bcc45afb-017a-46a3-b830-52c995e8ea44.png)

**Comment by LanceSandino** [comment]
This could be because the zoom Api v1 seems to not support 

```
 settings: {
          join_before_host: true,
          waiting_room: false,
        },
```
