### ISSUE TITLE
Failing to insert pinned messages from Slack - user missing

### ISSUE THREAD

**Issue by rwejdling** [echoboomer/incident-bot#268]
Hi,

We're experinecing an issue where the Slack integration is failing to insert the pinned messages do to a missing user ID. This might be an issue in the Slack App, but not sure how to fix it. It's working for at least one user, but haven't found a pattern.

We're running the latest release `v1.4.10`.

<img width="428" alt="image" src="https://github.com/echoboomer/incident-bot/assets/10534982/8b10b90f-c239-4bdb-8a48-f2d4540e12c7">

---

Application log output:

```
ERROR:slack.logging:Audit log row create failed for incident inc-202362793-test-pinning-in-channel: (psycopg2.errors.NotNullViolation) null value in column "user" of relation "incident_logging" violates not-null constraint

DETAIL:  Failing row contains (9, inc-202362793-test-pinning-in-channel, , then vi have a very important message, \x, , 27/06/2023 09:04:57 CEST, null).

[SQL: INSERT INTO incident_logging (incident_id, title, content, img, mimetype, ts, "user") VALUES (%(incident_id)s, %(title)s, %(content)s, %(img)s, %(mimetype)s, %(ts)s, %(user)s) RETURNING incident_logging.id]

[parameters: {'incident_id': 'inc-202362793-test-pinning-in-channel', 'title': '', 'content': 'then vi have a very important message', 'img': <psycopg2.extensions.Binary object at 0x7fd41d8ef030>, 'mimetype': '', 'ts': '27/06/2023 09:04:57 CEST', 'user': None}]
```

**Comment by LanceSandino** [comment]
We had a similar issue but when posting an image. Haven’t had a chance to test again but if I can replicate I’ll repost.

**Comment by rwejdling** [comment]
I just tried to reproduce on `v1.4.19` (or install has been lying dormant for a while due to this issue). And for now it doesn't seem the have the same issue.

Any chance that this has been fixed in one of the recent releases?

**Comment by echoboomer** [comment]
> I just tried to reproduce on `v1.4.19` (or install has been lying dormant for a while due to this issue). And for now it doesn't seem the have the same issue.
> 
> Any chance that this has been fixed in one of the recent releases?

This is likely the case. Please open a new issue if this happens again. Thanks for reporting!
