### ISSUE TITLE
App home view in Slack shows an error when many incidents are open

### ISSUE THREAD

**Issue by echoboomer** [echoboomer/incident-bot#307]
```bash
incident-bot-7fbcc8c89-nqsrq incident-bot 07-25 14:08:07 ERROR:handler.py:update_home_tab:Error publishing home tab: The request to the Slack API failed. (url: https://www.slack.com/api/views.publish)
incident-bot-7fbcc8c89-nqsrq incident-bot 07-25 14:08:07 The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] failed to match all allowed schemas [json-pointer:/view]', '[ERROR] no more than 5 items allowed [json-pointer:/view/blocks/20/accessory/options]', '[ERROR] no more than 5 items allowed [json-pointer:/view/blocks/21/accessory/options]', '[ERROR] no more than 5 items allowed [json-pointer:/view/blocks/22/accessory/options]', '[ERROR] no more than 5 items allowed [json-pointer:/view/blocks/23/accessory/options]']}}
```

**Comment by LanceSandino** [comment]
Hi. Any update on this? It’s very monitor but makes the home page useless (especially when showing stale data)

**Comment by echoboomer** [comment]
@LanceSandino from a user perspective, do you or your team use the bot's web UI at all? It would be easiest to not include this information on the app home but instead link to the UI where all incidents can be listed and pagination is already supported. I'm not sure there's a graceful way to handle this problem on the app home since there will always be a limitation on blocks.

**Comment by LanceSandino** [comment]
No we don’t use the GUI because of no support for openid/saml. 

In my opinion, the homepage would be great to show the types of roles, links to pages, and open incidents (even if it’s truncated) 

PagerDuty imo is not necessary as you can use the `pager` function once that’s fixed.

**Comment by LanceSandino** [comment]
In my org honestly we don’t use the home page either since it hasn’t worked for us since day one. 
but would love to be able to use it.

**Comment by echoboomer** [comment]
@LanceSandino thanks for the feedback. I will work on fixing the app home regardless. On a side note, I will investigate adding support for OIDC to the GUI.

**Comment by echoboomer** [comment]
@LanceSandino release `v1.4.21` should resolve this - let me know if you have a chance to test!

**Comment by LanceSandino** [comment]
looks like it's working! 🙌🏽 

<img width="1057" alt="image" src="https://github.com/echoboomer/incident-bot/assets/1300195/47a5b0f9-7f72-4379-a34a-6482326a75e0">
