### ISSUE TITLE
Pushpin feature not working with custom channel names

### ISSUE THREAD

**Issue by rwejdling** [echoboomer/incident-bot#408]
Hi,

After we started using the new custom channel name feature i noticed that the pushpin feature (saving messages to timeline) stopped working. 

I found that case handling the pushpin reaction has a condition that the channel name starts with `inc-` and our channel names now start with `incident-`.

Could we change this to use the `channel_name_prefix` config item in stead?

https://github.com/echoboomer/incident-bot/blob/main/backend/bot/slack/handler.py#L409

**Comment by echoboomer** [comment]
@rwejdling thanks for reporting this bug! I have released version `v1.8.1` that should fix this.
