### ISSUE TITLE
[FEATURE] Disable tracking in digest channel

### ISSUE THREAD

**Issue by rwejdling** [echoboomer/incident-bot#416]
**Is your feature request related to a problem? Please describe.**
We've just gone live with incident-bot and replaced our old incident manager bot. We're using the main engineering channel (with more that 400 members) as the digest channel to ensure people are notified when a incident i opened (yes, we don't have a lot of incidents). This means that we're continuously getting the notification below:

![image](https://github.com/echoboomer/incident-bot/assets/10534982/c35717e2-bf7f-45b3-86a1-bfc9922a366e)

We would prefer to keep the main channel as our incident channel as incident bot has a nice level of information. 

**Describe the solution you'd like**
A config option to disable tracking of chatter in the digest channel (or at least ignore it). https://github.com/echoboomer/incident-bot/blob/main/backend/bot/slack/handler.py#L521-L565

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rwejdling** [comment]
Ahh... there's already a PR for this 👍 

#412

**Comment by echoboomer** [comment]
Honestly, this feature isn't really useful anymore and could stand to be removed. I'm going to cut a release that will do that and let you know.

**Comment by echoboomer** [comment]
@rwejdling `v1.8.3` is now live with a new chart version and removes the chatter feature. Thanks for reporting!

**Comment by rwejdling** [comment]
Thanks a lot! Will deploy it tomorrow 👍
