### ISSUE TITLE
[FEATURE] Possibility to use my own Confluence template

### ISSUE THREAD

**Issue by luismartins-td** [echoboomer/incident-bot#419]
**Is your feature request related to a problem? Please describe.**
Instead of having only one template, be possible to use my template from my confluence

**Comment by echoboomer** [comment]
For this feature, are you looking to provide the template code locally to the bot like we already do here or are you looking to create a template in Confluence and have the bot import it?

**Comment by ImDevinC** [comment]
@echoboomer I would like to create a template in Confuence and have the bot import it. I think this will be easier for most people as well, since they can use Confluence to create what they want to see versus having to export the HTML and provide it as a config object

**Comment by uptickmetachu** [comment]
I can also see an alternative implementation where the document is provided as a jinja template. 

Happy to help contribute with either of these features.

**Comment by echoboomer** [comment]
This has been fixed in release v2.0.0.
