### ISSUE TITLE
[FEATURE] - Possibility to specify the RCA Confluence page name

### ISSUE THREAD

**Issue by luismartins-td** [echoboomer/incident-bot#420]
**Is your feature request related to a problem? Please describe.**
Be possible to specify the RCA Confluence page name as we can specify in the channel.

**Comment by echoboomer** [comment]
Can you elaborate on what you're asking here? Are you asking to have control over what the RCA children page titles are that the bot creates for incidents?

**Comment by luismartins-td** [comment]
Yes. I want to specify the title of the RCA page.

**Comment by echoboomer** [comment]
This has been fixed in release v2.0.0.
