### ISSUE TITLE
[BUG] DB migration in 1.9.0 not working

### ISSUE THREAD

**Issue by rwejdling** [echoboomer/incident-bot#452]
**Describe the bug**
Trying to upgrade from v1.8.3 using `make run_migrations` as mentioned in #425 and it results in a error

```
psycopg2.errors.DuplicateColumn: column "is_security_incident" of relation "incidents" already exists
```

Related bug report: https://github.com/echoboomer/incident-bot/issues/444

**Version**

1.8.3 and trying to upgrade to > 1.9.0

**To Reproduce**

1. Stop the container running 1.8.3
2. Checkout codebase from tags/v1.9.0 (also tried with the v1.10.1 with same result
3. Put Postgress credentials in env vars
3. `cd backend && make run_migrations` (no make target found in the root Makefile)

Error:

```
...
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> ca70b39d39ed, Add security column to Incidents table
Traceback (most recent call last):
  File "/home/ssm-user/incident-bot/backend/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/ssm-user/incident-bot/backend/venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateColumn: column "is_security_incident" of relation "incidents" already exists
....
```

**Expected behavior**
No errors

**Environment (please complete the following information):**
 - Platform: running migration script from a Amazon Linux 2023 instance
 - Hosting incident-bot contianer in ECS (not related to this bug)

**Comment by rwejdling** [comment]
I'm assuming that it's only the [00417e13021a_rename_rca_to_postmortem.py](https://github.com/echoboomer/incident-bot/blob/main/backend/alembic/versions/00417e13021a_rename_rca_to_postmortem.py) migration that I'm missing, so how do I tell alembic only to apply that?

**Comment by echoboomer** [comment]
This happens because the `alembic_version` table isn't present in the database so it assumes it has to run all of the migrations. You can either alter the `incidents` table to change the column name manually, or you can just delete all of the migration files except for the one you want to run and remove the downgrade version:

```python
"""Add sp_incident_data column to Incidents table

Revision ID: d1258401df8c
Revises:
Create Date: 2023-02-04 20:24:45.271119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1258401df8c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("incidents", sa.Column("sp_incident_data", sa.JSON()))


def downgrade():
    pass
```

**Comment by rwejdling** [comment]
Removing all migration files and changing `down_revision = None` did the trick. Thanks! After a few attempts of updating the config file with the latest changes we've now got `1.10.1` up and running. 

Any idea why there was no `alembic_version` table in our setup? The schema has been applied by the app at first run.

**Comment by echoboomer** [comment]
If you've never run a migration it won't be there. If you're running the latest version it wouldn't need to run any of them. That is probably something that needs to be improved.
