### ISSUE TITLE
[BUG] Timestamp mismatch

### ISSUE THREAD

**Issue by rwejdling** [echoboomer/incident-bot#453]
**Describe the bug**
Timestamp in incident updates aren't matching the configured timezone. 

**Version**
1.10.1 and previous versions (just never got around to reporting it)

**To Reproduce**
1. Set `timezone: CET` or `timezone: Europe/Copenhagen` in `config.yaml`
2. Post an update on a incident
3. Validate that the `Posted At:` timestamp on the update in digest channel is actually correct

**Expected behavior**
Set `posted at` to the correct timestamp

**Screenshots**
![image](https://github.com/echoboomer/incident-bot/assets/10534982/74248011-daa4-4757-aa91-e242e4598d22)

**Environment (please complete the following information):**
 - Platform: container running on ECS

**Additional context**
N/A

**Comment by rwejdling** [comment]
Actually all timestamps are one hour off:
<img width="689" alt="image" src="https://github.com/echoboomer/incident-bot/assets/10534982/eee6d9a2-a09a-408b-8ba0-eb1b147df625">
<img width="473" alt="image" src="https://github.com/echoboomer/incident-bot/assets/10534982/aafbd1b2-bfb9-4163-a380-354ef4ad7ac2">

**Comment by uptickmetachu** [comment]
I believe this might be because all the timestamps are currently stored as strings with the timestamp embedded in them:

updated_at is  `2024-02-13T20:53:20 AEDT`.

Would it be feasible to refactor the time columns from string/varchar to utc timestamps and then render them to the users specified timezone? @echoboomer

**Comment by uptickmetachu** [comment]
```
application_timezone = 'Europe/Copenhagen'


def fetch_timestamp(short: bool = False):
    """Return a localized, formatted timestamp using datetime.now()"""
    now = datetime.now()
    localized = timezone(application_timezone).localize(now)
    if short:
        return localized.strftime(timestamp_fmt_short)
    return localized.strftime(timestamp_fmt)
```

This seems to be the problem.

https://github.com/echoboomer/incident-bot/blob/ec7b1160e9a8b161175aa174f08499c1d21921b9/backend/bot/shared/tools.py#L22

This should be 
```

    now = datetime.datetime.now(datetime.UTC)
    localized = now.astimezone(timezone(application_timezone))
    if short:
        return localized.strftime(timestamp_fmt_short)
    return localized.strftime(timestamp_fmt)
```

**Comment by echoboomer** [comment]
@rwejdling I just released https://github.com/echoboomer/incident-bot/releases/tag/v1.12.2 which should handle this. If not, please reopen and let me know. Thanks for reporting it.

**Comment by uptickmetachu** [comment]
Sorry for not being able to get this one through L(

**Comment by echoboomer** [comment]
> Sorry for not being able to get this one through L(

No worries! I wouldn't expect you to. I finally had some time to catch up and tried to give it a shot.
