### ISSUE TITLE
[FEATURE] Refactor serializers to pydantic

### ISSUE THREAD

**Issue by uptickmetachu** [echoboomer/incident-bot#459]
What are your thouhgts on refactoring the serializers to `pydantic` instead of marshmallow? I would be happy to make a PR if you thought it woudl be useful.

https://docs.pydantic.dev/latest/

I can see several benefits:
1. Better type hints throughout the code base. The code currently uses the following settings access patern. 

```python
config.active.integrations.get("atlassian")
.get("confluence")
.get("space"),
```
It would be advantageous to get the proper types instead of relying on default getters. This would simplify refactoring and provide extra safety.

2. Better configuration parsing. 
Currently configuration must come from `config.yaml` and environment variables. For improved flexibility and testing ergonomics it would be nice to to set configuration from a config.yaml with environment variable overrides. [Pydantic's settings management](https://docs.pydantic.dev/latest/concepts/pydantic_settings/) is both powerful and flexible.

3. Generating pydantic models from 3rd party (confluence/jira/opsgenie/pagerduty) apis will also improve DX + type safety.

Love to hear your thoughts :).

**Comment by echoboomer** [comment]
@uptickmetachu Thanks for the contribution. I'll check this out as soon as I can.

**Comment by echoboomer** [comment]
@uptickmetachu sorry it took me a bit to get back to you - honestly, after doing some work on a project I just built, it might even be worth implementing FastAPI in-place of the bespoke Flask implementation which would also make it easier to implement Pydantic models. Any thoughts?

**Comment by uptickmetachu** [comment]
I'll be honest, I have written a mostly working version from ground up incident slack bot using fast-api, sqlmodel etc with the goal of everything being type safe. I haven't gotten around to using it as I haven't had time (as well!) to finish it off. 

Would love to collaborate or share ideas.
