### ISSUE TITLE
[BUG] Too many pagerduty schedules causes `/incident pager` command to time out

### ISSUE THREAD

**Issue by ImDevinC** [echoboomer/incident-bot#470]
**Describe the bug**
We have 16 schedules in PagerDuty, and when we run `/incident pager` the command times out. In the log I see the following messages
```
PagerDuty returned 15 schedules
Error: The request to the Slack API failed. (url: https://www.slack.com/api/views.open) The server responded with {'ok': False, 'error': 'expired_trigger_id'}
```

**Version**
`1.10.1`

**To Reproduce**
1. Create 15 schedules in PagerDuty
2. Type `/incident pager`

**Expected behavior**
Modal should popup

**Environment (please complete the following information):**
- Platform: Kubernetes

**Additional context**
I'm not 100% sure that 15 schedules causes it, could be the number of users per schedule or something else

**Comment by echoboomer** [comment]
@ImDevinC sorry it took me so long to get to this. I just released `v1.12.0` which should resolve this. The pager command now pulls from the copy of the pd info in the db instead of calling the API each time. Please let me know if not. Thanks!
