### ISSUE TITLE
fix(slack_app_manifest): files:read is missing

### ISSUE THREAD

**Issue by virgileJT** [echoboomer/incident-bot#77]
Hello here :)
that's a very nice project !
One thought, I think the files:read is missing, as I've seen the files:write in slack_app_manifest.yaml but the read is required to save the attachment in db (otherwise we have a default slack html content).
Cheers !

**Comment by echoboomer** [comment]
@virgileJT this actually ended up being an issue with how the image was retrieved from Slack which will be resolved in this latest release. Check out the release notes if you want more details! Thanks for reporting the error.
