### ISSUE TITLE
fix(attachments): Attachments not displayed on FO

### ISSUE THREAD

**Issue by virgileJT** [echoboomer/incident-bot#88]
@virgileJT thanks for reporting, transferred this to an issue and I'll check it out.

_Originally posted by @echoboomer in https://github.com/echoboomer/incident-bot/discussions/78#discussioncomment-4426369_

**Comment by virgileJT** [comment]
With some help we manage to create a new React component and get the image with token : 

in frontend/src/incident/Single-incident.js replace
                                <img src={`${item.img}`} alt={item.title} loading="lazy" />
with 
                                <AttachmentImage item={item} token={token} />
and add this import on top
import AttachmentImage from './components/Attachment-image.component.js';

create frontend/src/incident/components/Attachment-image.component.js
import React, { useEffect, useState } from 'react';
import axios from 'axios';

export default function AttachmentImage({ item, token }) {
  const [attachmentImage, setAttachmentImage] = useState(null);

  useEffect(() => {
    (async () => {
      const response = await axios({
        method: 'GET',
        responseType: 'arraybuffer',
        url: item.img,
        headers: {
          Authorization: 'Bearer ' + token
        }
      });
      setAttachmentImage(btoa(String.fromCharCode.apply(null, new Uint8Array(response.data))));
    })();
  }, []);

  return <img src={`data:image/jpeg;base64,${attachmentImage}`} alt={item.title} loading="lazy" />;
}

**Comment by echoboomer** [comment]
@virgileJT thanks for the submission, I was able to handle this issue a different way. I'd also advising you rebase as the way the images were stored in Slack was also broken in most cases due to link handling.
